import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, HeartHandshake, Users } from "lucide-react";
import { CtaBand, Checklist, PageHero, SectionTitle } from "../components/site-components";
import foundation from "../assets/vikshana-foundation.jpg";

export const Route=createFileRoute("/about")({head:()=>({meta:[{title:"About Vikshana Eye Hospital | Eye Care Centre in Yelahanka"},{name:"description",content:"Learn about Vikshana Eye Hospital, a patient-first eye care centre and ophthalmology clinic in Yelahanka. Our vision, mission and commitment to compassionate, comprehensive eye care."},{name:"keywords",content:"Eye Hospital, Eye Clinic, Eye Care Centre, Ophthalmology Hospital, Ophthalmology Clinic, Comprehensive Eye Care"},{property:"og:title",content:"About Vikshana Eye Hospital"},{property:"og:description",content:"Our vision, mission and commitment to ethical, compassionate eye care in Bengaluru."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/about"}]}),component:About});

const aboutLinks = [
  { to: "/about/vikshana-foundation", icon: HeartHandshake, eyebrow: "Vikshana Foundation", title: "Our journey and commitment to responsible care", text: "Discover the story behind Vikshana Eye Hospital and the values that guide our journey." },
  { to: "/about/our-management", icon: Users, eyebrow: "Leadership", title: "Meet Our Management", text: "Get to know the leadership guiding our clinical standards and patient care." },
] as const;

function About(){return <><PageHero eyebrow="About us" title="Eye care guided by clarity, respect and compassion" text="Vikshana Eye Hospital is a patient-focused ophthalmology centre in Yelahanka, Bengaluru, offering thoughtful evaluation and care in a welcoming clinical environment."/><section className="section-pad"><div className="mx-auto grid max-w-7xl items-center gap-12 px-4 sm:px-6 lg:grid-cols-2"><div><SectionTitle eyebrow="Who we are" title="About VIKSHANA EYE HOSPITAL" text="We believe good eye care begins with listening. Our approach brings together professional expertise, careful evaluation, ethical practice and clear communication so that patients can make informed decisions about their vision."/><p className="mt-5 leading-7 text-muted-foreground">From routine vision assessment to specialized consultation and surgical care, our goal is to make each visit calm, understandable and centered on the individual.</p></div><img src={foundation} alt="Doctor speaking compassionately with a patient" className="aspect-[4/3] size-full rounded-lg object-cover shadow-xl"/></div></section><section className="section-pad bg-muted"><div className="mx-auto grid max-w-7xl gap-8 px-4 sm:px-6 lg:grid-cols-2"><article className="rounded-lg bg-background p-8"><SectionTitle eyebrow="Our vision" title="A clearer, healthier and more confident life"/><p className="mt-5 leading-7 text-muted-foreground">To help people experience a clearer, healthier and more confident life through accessible and compassionate eye care.</p></article><article className="rounded-lg bg-background p-8"><SectionTitle eyebrow="Our mission" title="Care that puts patients first"/><Checklist items={["Patient-first and respectful care","Comprehensive eye evaluation","Ethical medical practice","Professional expertise","Modern clinical practices","Clear patient education"]}/></article></div></section><section className="section-pad"><div className="mx-auto max-w-7xl px-4 sm:px-6"><SectionTitle eyebrow="Learn more" title="Our story and our people" center/><div className="mt-10 grid gap-6 md:grid-cols-2">{aboutLinks.map(({to,icon:Icon,eyebrow,title,text})=><Link key={to} to={to} className="group flex flex-col rounded-lg border border-border bg-card p-8 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-lg"><span className="grid size-14 place-items-center rounded-md bg-accent text-primary"><Icon/></span><p className="mt-6 text-sm font-bold uppercase tracking-widest text-primary">{eyebrow}</p><h3 className="mt-2 text-2xl font-bold text-brand-deep">{title}</h3><p className="mt-3 leading-7 text-muted-foreground">{text}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-primary">Read More <ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></span></Link>)}</div></div></section><CtaBand/></>}
