import { Link } from "@tanstack/react-router";
import { ArrowRight, CalendarDays, CheckCircle2 } from "lucide-react";
import { Button } from "./ui/button";
import { services } from "../lib/site-data";

export function PageHero({eyebrow,title,text}:{eyebrow:string,title:string,text:string}){return <section className="bg-brand-deep text-primary-foreground"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 sm:py-28"><p className="mb-4 text-sm font-bold uppercase tracking-widest text-brand-warm">{eyebrow}</p><h1 className="max-w-4xl text-4xl leading-tight sm:text-6xl">{title}</h1><p className="mt-5 max-w-2xl text-base leading-8 opacity-80 sm:text-lg">{text}</p></div></section>}
export function SectionTitle({eyebrow,title,text,center=false}:{eyebrow?:string,title:string,text?:string,center?:boolean}){return <div className={center?"mx-auto max-w-3xl text-center":"max-w-3xl"}>{eyebrow&&<p className="mb-3 text-sm font-bold uppercase tracking-widest text-primary">{eyebrow}</p>}<h2 className="text-3xl leading-tight text-brand-deep sm:text-5xl">{title}</h2>{text&&<p className="mt-4 leading-7 text-muted-foreground">{text}</p>}</div>}
export function ServiceGrid({limit}:{limit?:number}){return <div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{services.slice(0,limit).map(({name,text,icon:Icon})=><article key={name} className="group rounded-lg border border-border bg-card p-6 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-lg"><span className="grid size-12 place-items-center rounded-md bg-accent text-primary"><Icon/></span><h3 className="mt-5 text-lg font-bold text-brand-deep">{name}</h3><p className="mt-3 min-h-14 text-sm leading-6 text-muted-foreground">{text}</p><Link to="/services" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-primary">Learn More <ArrowRight className="size-4"/></Link></article>)}</div>}
export function PlaceholderCard({role,doctor=false}:{role:string,doctor?:boolean}){return <article className="rounded-lg border border-border bg-card p-6 shadow-sm"><div className="grid aspect-[4/3] place-items-center rounded-md bg-brand-soft text-center text-sm font-semibold text-muted-foreground">Professional photograph<br/>to be added</div><p className="mt-5 text-xs font-bold uppercase tracking-widest text-primary">{role}</p><h3 className="mt-2 text-xl font-bold text-brand-deep">{doctor?"Dr. [Doctor Name]":"[Name to be added]"}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">[Qualifications] · [Specialization / professional profile]</p><Button asChild variant="soft" className="mt-5 w-full"><Link to="/contact">{doctor?"Book Appointment":"View Profile"}</Link></Button></article>}
export function CtaBand(){return <section className="bg-primary text-primary-foreground"><div className="mx-auto grid max-w-7xl items-center gap-6 px-4 py-12 sm:px-6 md:grid-cols-[1fr_auto]"><div><h2 className="font-sans text-2xl font-bold">Ready to care for your vision?</h2><p className="mt-2 opacity-85">Request an appointment with our eye-care team in Yelahanka.</p></div><Button asChild size="lg" variant="secondary"><Link to="/contact"><CalendarDays/>Book an Appointment</Link></Button></div></section>}
export function Checklist({items}:{items:string[]}){return <ul className="mt-6 grid gap-3">{items.map(i=><li key={i} className="flex gap-3 text-sm leading-6"><CheckCircle2 className="mt-0.5 size-5 shrink-0 text-primary"/>{i}</li>)}</ul>}