import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { Menu, X, Phone, MessageCircle, Instagram, Facebook, Youtube, MapPin, Mail } from "lucide-react";
import { Button } from "./ui/button";
import logo from "../assets/vikshana-logo.png.asset.json";
import { contact, services, whatsapp } from "../lib/site-data";

const links = [["Home","/"],["About Us","/about"],["Our Doctors","/doctors"],["Our Services","/services"],["Shades Optical Shop","/shades-optical"],["Contact Us","/contact"]] as const;
export function SiteHeader(){
  const [open,setOpen]=useState(false);
  return <header className="sticky top-0 z-50 border-b border-border/70 bg-background/95 backdrop-blur-xl">
    <div className="bg-brand-deep text-primary-foreground"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-2 text-xs sm:px-6"><span className="flex items-center gap-2"><MapPin className="size-3.5"/>Yelahanka, Bengaluru</span><a className="flex items-center gap-2 font-semibold" href={`tel:${contact.phone1}`}><Phone className="size-3.5"/>Call {contact.phone1}</a></div></div>
    <div className="mx-auto grid h-20 max-w-7xl grid-cols-[minmax(0,1fr)_auto] items-center gap-4 px-4 sm:px-6">
      <Link to="/" className="flex min-w-0 items-center gap-3" onClick={()=>setOpen(false)}><img src={logo.url} alt="Vikshana Eye Hospital logo" className="h-12 w-12 shrink-0 object-contain"/><span className="min-w-0"><strong className="block truncate text-sm font-extrabold text-brand-deep sm:text-base">VIKSHANA EYE HOSPITAL</strong><small className="block text-xs text-muted-foreground">Clear Vision. Better Life.</small></span></Link>
      <nav className="hidden items-center gap-1 lg:flex" aria-label="Primary navigation">{links.map(([label,to])=><Link key={to} to={to} className="rounded-md px-3 py-2 text-sm font-semibold text-muted-foreground hover:bg-accent hover:text-foreground" activeProps={{className:"bg-accent text-foreground"}} activeOptions={{exact:to==="/"}}>{label}</Link>)}<Button asChild className="ml-2"><Link to="/contact">Book an Appointment</Link></Button></nav>
      <Button variant="ghost" size="icon" className="min-h-11 min-w-11 lg:hidden" aria-label={open?"Close menu":"Open menu"} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</Button>
    </div>
    {open&&<nav className="border-t border-border bg-background px-4 py-4 lg:hidden" aria-label="Mobile navigation"><div className="mx-auto grid max-w-7xl gap-1">{links.map(([label,to])=><Link key={to} to={to} onClick={()=>setOpen(false)} className="rounded-md px-4 py-3 font-semibold hover:bg-accent">{label}</Link>)}<Button asChild size="lg" className="mt-2"><Link to="/contact" onClick={()=>setOpen(false)}>Book an Appointment</Link></Button></div></nav>}
  </header>;
}
export function SiteFooter(){return <footer className="bg-brand-deep text-primary-foreground"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 md:grid-cols-2 lg:grid-cols-4"><div><div className="flex items-center gap-3"><img src={logo.url} alt="" className="h-14 w-14 object-contain"/><strong>VIKSHANA<br/>EYE HOSPITAL</strong></div><p className="mt-4 text-sm leading-7 opacity-80">Comprehensive eye care with compassion, clarity and a patient-first approach.</p><div className="mt-5 flex gap-2">{[Instagram,Facebook,Youtube].map((Icon,i)=><a key={i} href="#" aria-label={["Instagram","Facebook","YouTube"][i]} className="grid size-10 place-items-center rounded-md border border-primary-foreground/20 hover:bg-primary-foreground/10"><Icon className="size-4"/></a>)}</div></div><div><h2 className="font-sans text-base font-bold">Quick Links</h2><div className="mt-4 grid gap-3 text-sm opacity-80">{links.slice(1).map(([l,t])=><Link key={t} to={t} className="hover:opacity-100">{l}</Link>)}</div></div><div><h2 className="font-sans text-base font-bold">Our Services</h2><div className="mt-4 grid gap-3 text-sm opacity-80">{services.slice(2,9).map(s=><Link key={s.name} to="/services">{s.name}</Link>)}</div></div><div><h2 className="font-sans text-base font-bold">Contact</h2><div className="mt-4 grid gap-4 text-sm leading-6 opacity-85"><a href={`tel:${contact.phone1}`} className="flex gap-3"><Phone className="mt-1 size-4 shrink-0"/>{contact.phone1}<br/>{contact.phone2}</a><a href={`mailto:${contact.email}`} className="flex gap-3"><Mail className="mt-1 size-4 shrink-0"/>{contact.email}</a><p className="flex gap-3"><MapPin className="mt-1 size-4 shrink-0"/>{contact.address}</p></div></div></div><div className="border-t border-primary-foreground/10 px-4 py-5 text-center text-xs opacity-70">© 2026 Vikshana Eye Hospital. All rights reserved.</div></footer>}
export function WhatsAppButton(){return <a href={whatsapp} target="_blank" rel="noreferrer" aria-label="Enquire on WhatsApp" className="fixed bottom-5 right-5 z-40 grid size-14 place-items-center rounded-full bg-primary text-primary-foreground shadow-xl transition-transform hover:scale-105"><MessageCircle/></a>}