import { Link } from "@tanstack/react-router";
import { ArrowRight, Award, CheckCircle2, Phone, Star } from "lucide-react";
import { Button } from "./ui/button";
import { contact, services, type Doctor, type ManagementProfile } from "../lib/site-data";

export function PageHero({eyebrow,title,text}:{eyebrow:string,title:string,text:string}){return <section className="bg-brand-deep text-primary-foreground"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 sm:py-28"><p className="mb-4 text-sm font-bold uppercase tracking-widest text-brand-warm">{eyebrow}</p><h1 className="max-w-4xl text-4xl leading-tight sm:text-6xl">{title}</h1><p className="mt-5 max-w-2xl text-base leading-8 opacity-80 sm:text-lg">{text}</p></div></section>}
export function SectionTitle({eyebrow,title,text,center=false}:{eyebrow?:string,title:string,text?:string,center?:boolean}){return <div className={center?"mx-auto max-w-3xl text-center":"max-w-3xl"}>{eyebrow&&<p className="mb-3 text-sm font-bold uppercase tracking-widest text-primary">{eyebrow}</p>}<h2 className="text-3xl leading-tight text-brand-deep sm:text-5xl">{title}</h2>{text&&<p className="mt-4 leading-7 text-muted-foreground">{text}</p>}</div>}
export function ServiceGrid({limit}:{limit?:number}){return <div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{services.slice(0,limit).map(({name,text,icon:Icon,slug,image,alt})=><article key={slug} className="group overflow-hidden rounded-lg border border-border bg-card shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-lg"><Link to="/services/$slug" params={{slug}} className="block"><img src={image} alt={alt} loading="lazy" width={1280} height={960} className="aspect-[16/10] w-full object-cover"/><div className="p-6"><span className="grid size-12 place-items-center rounded-md bg-accent text-primary"><Icon/></span><h3 className="mt-5 text-lg font-bold text-brand-deep">{name}</h3><p className="mt-3 min-h-14 text-sm leading-6 text-muted-foreground">{text}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-primary">Learn More <ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></span></div></Link></article>)}</div>}
export function PlaceholderCard({role,doctor=false}:{role:string,doctor?:boolean}){return <article className="rounded-lg border border-border bg-card p-6 shadow-sm"><div className="grid aspect-[4/3] place-items-center rounded-md bg-brand-soft text-center text-sm font-semibold text-muted-foreground">Professional photograph<br/>to be added</div><p className="mt-5 text-xs font-bold uppercase tracking-widest text-primary">{role}</p><h3 className="mt-2 text-xl font-bold text-brand-deep">{doctor?"Dr. [Doctor Name]":"[Name to be added]"}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">[Qualifications] · [Specialization / professional profile]</p><Button asChild variant="soft" className="mt-5 w-full"><Link to="/contact">{doctor?"Contact the Hospital":"View Profile"}</Link></Button></article>}
export function ProfileAvatar({photo,initials,name,size="md"}:{photo?:string,initials:string,name:string,size?:"md"|"lg"}){
  const dim = size==="lg" ? "size-32 sm:size-40" : "size-20";
  if(photo)return <img src={photo} alt={name} className={`${dim} shrink-0 rounded-full object-cover object-top shadow-lg ring-4 ring-primary-foreground/30`}/>;
  return <span className={`grid ${dim} shrink-0 place-items-center rounded-full bg-gradient-to-br from-primary to-brand-deep font-display font-bold text-primary-foreground shadow-lg ring-4 ring-primary-foreground/20 ${size==="lg"?"text-4xl sm:text-5xl":"text-lg"}`}>{initials}</span>;
}
export function TagList({items}:{items:string[]}){return <div className="flex flex-wrap gap-2">{items.map(t=><span key={t} className="rounded-full bg-accent px-3 py-1.5 text-xs font-bold uppercase tracking-wide text-primary">{t}</span>)}</div>}
export function HighlightList({items}:{items:string[]}){return <div className="grid gap-3 sm:grid-cols-2">{items.map(h=><div key={h} className="flex items-start gap-3 rounded-lg border border-border bg-card p-4 shadow-sm"><Award className="mt-0.5 size-5 shrink-0 text-primary"/><span className="text-sm leading-6 text-foreground">{h}</span></div>)}</div>}
export function ManagementCard({profile}:{profile:ManagementProfile}){return <article className="group flex flex-col items-center rounded-lg border border-border bg-card p-8 text-center shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-lg"><ProfileAvatar photo={profile.photo} initials={profile.initials} name={profile.name}/><p className="mt-6 text-xs font-bold uppercase tracking-widest text-primary">{profile.role}</p><h3 className="mt-2 text-xl font-bold text-brand-deep">{profile.name}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{profile.credentials[0]}</p><div className="mt-4 flex flex-wrap justify-center gap-1.5">{profile.tags.slice(0,3).map(t=><span key={t} className="rounded-full bg-accent px-2.5 py-1 text-[11px] font-bold uppercase tracking-wide text-primary">{t}</span>)}</div><Button asChild variant="soft" className="mt-6 w-full"><Link to="/about/our-management/$slug" params={{slug:profile.slug}}>View Profile</Link></Button></article>}
export function DoctorCard({doctor}:{doctor:Doctor}){return <article className="group flex flex-col items-center rounded-lg border border-border bg-card p-8 text-center shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-lg"><ProfileAvatar photo={doctor.photo} initials={doctor.initials} name={doctor.name}/><p className="mt-6 text-xs font-bold uppercase tracking-widest text-primary">{doctor.role}</p><h3 className="mt-2 text-xl font-bold text-brand-deep">{doctor.name}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{doctor.credentials.join(" · ")}</p><div className="mt-4 flex flex-wrap justify-center gap-1.5">{doctor.tags.slice(0,3).map(t=><span key={t} className="rounded-full bg-accent px-2.5 py-1 text-[11px] font-bold uppercase tracking-wide text-primary">{t}</span>)}</div><div className="mt-6 grid w-full gap-2"><Button asChild className="w-full"><Link to="/contact" search={{doctor:doctor.slug}}>Book Appointment</Link></Button><Button asChild variant="soft" className="w-full"><Link to="/doctors/$slug" params={{slug:doctor.slug}}>View Profile</Link></Button></div></article>}
export function CtaBand(){return <section className="bg-primary text-primary-foreground"><div className="mx-auto grid max-w-7xl items-center gap-6 px-4 py-12 sm:px-6 md:grid-cols-[1fr_auto]"><div><h2 className="font-sans text-2xl font-bold">Ready to care for your vision?</h2><p className="mt-2 opacity-85">Speak with our eye-care team in Yelahanka or visit us during clinic hours.</p></div><div className="flex flex-wrap gap-3"><Button asChild size="lg" variant="secondary"><a href={`tel:${contact.phone1}`}><Phone/>Call {contact.phone1}</a></Button><Button asChild size="lg" variant="hero"><Link to="/contact">Contact Us</Link></Button></div></div></section>}
export function Checklist({items}:{items:string[]}){return <ul className="mt-6 grid gap-3">{items.map(i=><li key={i} className="flex gap-3 text-sm leading-6"><CheckCircle2 className="mt-0.5 size-5 shrink-0 text-primary"/>{i}</li>)}</ul>}
export function Stars({rating}:{rating:number}){return <span className="flex gap-0.5" aria-label={`${rating} out of 5 stars`}>{[1,2,3,4,5].map(n=><Star key={n} className={`size-4 ${n<=rating?"fill-brand-warm text-brand-warm":"text-border"}`}/>)}</span>}
export function ReviewCard({name,source,rating,text}:{name:string,source:string,rating:number,text:string}){return <article className="flex h-full flex-col rounded-lg border border-border bg-card p-6 shadow-sm"><Stars rating={rating}/><p className="mt-4 flex-1 text-sm leading-7 text-muted-foreground">“{text}”</p><div className="mt-5 border-t border-border pt-4"><strong className="block text-sm text-brand-deep">{name}</strong><span className="text-xs font-semibold uppercase tracking-widest text-primary">via {source}</span></div></article>}
