/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ShadesOpticalRouteImport } from './routes/shades-optical'
import { Route as AboutOurManagementRouteImport } from './routes/about_.our-management'
import { Route as AboutVikshanaRouteImport } from './routes/about_.vikshana'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminDoctorsRouteImport } from './routes/admin.doctors'
import { Route as AdminOffersRouteImport } from './routes/admin.offers'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as DoctorsSlugRouteImport } from './routes/doctors_.$slug'
import { Route as ServicesSlugRouteImport } from './routes/services_.$slug'
import { Route as AboutOurManagementSlugRouteImport } from './routes/about_.our-management_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadesOpticalRoute = ShadesOpticalRouteImport.update({
  id: '/shades-optical',
  path: '/shades-optical',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutOurManagementRoute = AboutOurManagementRouteImport.update({
  id: '/about_/our-management',
  path: '/about/our-management',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutVikshanaRoute = AboutVikshanaRouteImport.update({
  id: '/about_/vikshana',
  path: '/about/vikshana',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsSlugRoute = DoctorsSlugRouteImport.update({
  id: '/doctors_/$slug',
  path: '/doctors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services_/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutOurManagementSlugRoute = AboutOurManagementSlugRouteImport.update({
  id: '/about_/our-management_/$slug',
  path: '/about/our-management/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/shades-optical': typeof ShadesOpticalRoute
  '/about/our-management': typeof AboutOurManagementRoute
  '/about/vikshana': typeof AboutVikshanaRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/login': typeof AdminLoginRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/about/our-management/$slug': typeof AboutOurManagementSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/shades-optical': typeof ShadesOpticalRoute
  '/about/our-management': typeof AboutOurManagementRoute
  '/about/vikshana': typeof AboutVikshanaRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/login': typeof AdminLoginRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/about/our-management/$slug': typeof AboutOurManagementSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/shades-optical': typeof ShadesOpticalRoute
  '/about_/our-management': typeof AboutOurManagementRoute
  '/about_/vikshana': typeof AboutVikshanaRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin_/login': typeof AdminLoginRoute
  '/doctors_/$slug': typeof DoctorsSlugRoute
  '/services_/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/about_/our-management_/$slug': typeof AboutOurManagementSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/doctors'
    | '/reviews'
    | '/services'
    | '/shades-optical'
    | '/about/our-management'
    | '/about/vikshana'
    | '/admin/campaigns'
    | '/admin/doctors'
    | '/admin/offers'
    | '/admin/login'
    | '/doctors/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/about/our-management/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/doctors'
    | '/reviews'
    | '/services'
    | '/shades-optical'
    | '/about/our-management'
    | '/about/vikshana'
    | '/admin/campaigns'
    | '/admin/doctors'
    | '/admin/offers'
    | '/admin/login'
    | '/doctors/$slug'
    | '/services/$slug'
    | '/admin'
    | '/about/our-management/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/doctors'
    | '/reviews'
    | '/services'
    | '/shades-optical'
    | '/about_/our-management'
    | '/about_/vikshana'
    | '/admin/campaigns'
    | '/admin/doctors'
    | '/admin/offers'
    | '/admin_/login'
    | '/doctors_/$slug'
    | '/services_/$slug'
    | '/admin/'
    | '/about_/our-management_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DoctorsRoute: typeof DoctorsRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRoute
  ShadesOpticalRoute: typeof ShadesOpticalRoute
  AboutOurManagementRoute: typeof AboutOurManagementRoute
  AboutVikshanaRoute: typeof AboutVikshanaRoute
  AdminLoginRoute: typeof AdminLoginRoute
  DoctorsSlugRoute: typeof DoctorsSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  AboutOurManagementSlugRoute: typeof AboutOurManagementSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shades-optical': {
      id: '/shades-optical'
      path: '/shades-optical'
      fullPath: '/shades-optical'
      preLoaderRoute: typeof ShadesOpticalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/our-management': {
      id: '/about_/our-management'
      path: '/about/our-management'
      fullPath: '/about/our-management'
      preLoaderRoute: typeof AboutOurManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/vikshana': {
      id: '/about_/vikshana'
      path: '/about/vikshana'
      fullPath: '/about/vikshana'
      preLoaderRoute: typeof AboutVikshanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors_/$slug': {
      id: '/doctors_/$slug'
      path: '/doctors/$slug'
      fullPath: '/doctors/$slug'
      preLoaderRoute: typeof DoctorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/$slug': {
      id: '/services_/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/our-management_/$slug': {
      id: '/about_/our-management_/$slug'
      path: '/about/our-management/$slug'
      fullPath: '/about/our-management/$slug'
      preLoaderRoute: typeof AboutOurManagementSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DoctorsRoute: DoctorsRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRoute,
  ShadesOpticalRoute: ShadesOpticalRoute,
  AboutOurManagementRoute: AboutOurManagementRoute,
  AboutVikshanaRoute: AboutVikshanaRoute,
  AdminLoginRoute: AdminLoginRoute,
  DoctorsSlugRoute: DoctorsSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  AboutOurManagementSlugRoute: AboutOurManagementSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
