/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ShadesOpticalRouteImport } from './routes/shades-optical'
import { Route as AboutOurManagementRouteImport } from './routes/about_.our-management'
import { Route as AboutVikshanaFoundationRouteImport } from './routes/about_.vikshana-foundation'
import { Route as DoctorsSlugRouteImport } from './routes/doctors_.$slug'
import { Route as ServicesSlugRouteImport } from './routes/services_.$slug'
import { Route as AboutOurManagementSlugRouteImport } from './routes/about_.our-management_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadesOpticalRoute = ShadesOpticalRouteImport.update({
  id: '/shades-optical',
  path: '/shades-optical',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutOurManagementRoute = AboutOurManagementRouteImport.update({
  id: '/about_/our-management',
  path: '/about/our-management',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutVikshanaFoundationRoute = AboutVikshanaFoundationRouteImport.update({
  id: '/about_/vikshana-foundation',
  path: '/about/vikshana-foundation',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsSlugRoute = DoctorsSlugRouteImport.update({
  id: '/doctors_/$slug',
  path: '/doctors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services_/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutOurManagementSlugRoute = AboutOurManagementSlugRouteImport.update({
  id: '/about_/our-management_/$slug',
  path: '/about/our-management/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/shades-optical': typeof ShadesOpticalRoute
  '/about/our-management': typeof AboutOurManagementRoute
  '/about/vikshana-foundation': typeof AboutVikshanaFoundationRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/about/our-management/$slug': typeof AboutOurManagementSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/shades-optical': typeof ShadesOpticalRoute
  '/about/our-management': typeof AboutOurManagementRoute
  '/about/vikshana-foundation': typeof AboutVikshanaFoundationRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/about/our-management/$slug': typeof AboutOurManagementSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/shades-optical': typeof ShadesOpticalRoute
  '/about_/our-management': typeof AboutOurManagementRoute
  '/about_/vikshana-foundation': typeof AboutVikshanaFoundationRoute
  '/doctors_/$slug': typeof DoctorsSlugRoute
  '/services_/$slug': typeof ServicesSlugRoute
  '/about_/our-management_/$slug': typeof AboutOurManagementSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/doctors'
    | '/reviews'
    | '/services'
    | '/shades-optical'
    | '/about/our-management'
    | '/about/vikshana-foundation'
    | '/doctors/$slug'
    | '/services/$slug'
    | '/about/our-management/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/doctors'
    | '/reviews'
    | '/services'
    | '/shades-optical'
    | '/about/our-management'
    | '/about/vikshana-foundation'
    | '/doctors/$slug'
    | '/services/$slug'
    | '/about/our-management/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/doctors'
    | '/reviews'
    | '/services'
    | '/shades-optical'
    | '/about_/our-management'
    | '/about_/vikshana-foundation'
    | '/doctors_/$slug'
    | '/services_/$slug'
    | '/about_/our-management_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DoctorsRoute: typeof DoctorsRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRoute
  ShadesOpticalRoute: typeof ShadesOpticalRoute
  AboutOurManagementRoute: typeof AboutOurManagementRoute
  AboutVikshanaFoundationRoute: typeof AboutVikshanaFoundationRoute
  DoctorsSlugRoute: typeof DoctorsSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  AboutOurManagementSlugRoute: typeof AboutOurManagementSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shades-optical': {
      id: '/shades-optical'
      path: '/shades-optical'
      fullPath: '/shades-optical'
      preLoaderRoute: typeof ShadesOpticalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/our-management': {
      id: '/about_/our-management'
      path: '/about/our-management'
      fullPath: '/about/our-management'
      preLoaderRoute: typeof AboutOurManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/vikshana-foundation': {
      id: '/about_/vikshana-foundation'
      path: '/about/vikshana-foundation'
      fullPath: '/about/vikshana-foundation'
      preLoaderRoute: typeof AboutVikshanaFoundationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors_/$slug': {
      id: '/doctors_/$slug'
      path: '/doctors/$slug'
      fullPath: '/doctors/$slug'
      preLoaderRoute: typeof DoctorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/$slug': {
      id: '/services_/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/our-management_/$slug': {
      id: '/about_/our-management_/$slug'
      path: '/about/our-management/$slug'
      fullPath: '/about/our-management/$slug'
      preLoaderRoute: typeof AboutOurManagementSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DoctorsRoute: DoctorsRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRoute,
  ShadesOpticalRoute: ShadesOpticalRoute,
  AboutOurManagementRoute: AboutOurManagementRoute,
  AboutVikshanaFoundationRoute: AboutVikshanaFoundationRoute,
  DoctorsSlugRoute: DoctorsSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  AboutOurManagementSlugRoute: AboutOurManagementSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
